name: code Coverage
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'JSON message'
        required: true
        default: '{}'
      prnumber:
        description: 'PR number string'
        required: true
permissions:
  pull-requests: write
jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 100

      - name: Install dependencies
        run: gem install bundler
      - name: Install Fastlane
        run: bundle install
        
      - name: Save message to file
        run: echo "${{ github.event.inputs.message }}" > fastlane/xcov_output/index.json

      - name: Run Fastlane
        run: bundle exec fastlane executeDangerWithPR token:${{ secrets.GITHUB_TOKEN }} pr:${{ github.event.inputs.prnumber }}


      # - name: Comment PR
      #   uses: thollander/actions-comment-pull-request@v2
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     message: |
      #       Hello world ! :wave:
      #     comment_tag: execution
      #     pr_number: 1
